---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
    component: app
    environment: prod
  name: app-prod
  namespace: smb-tst
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
      component: app
      environment: prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-app
        component: app
        environment: prod
    spec:
      containers:
        - image: smbtst:1
          imagePullPolicy: Always
          name: app-prod
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
